services:
  orchestrator_2:
    build: .
    container_name: orchestrator_2
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./credentials:/app/credentials
      - ./secrets:/app/secrets
      - .:/app
      - /app/.venv
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: orchestrator_redis
    restart: always
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"