[project]
name = "orchestrator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "google-auth>=2.47.0",
    "httpx>=0.28.1",
    "image>=1.5.33",
    "requests>=2.32.5",
    "uvicorn>=0.40.0",
]
